In [56]:
#load libraries 
import numpy as np
import scipy.sparse as sp
import cplex as cp

In [57]:
def linear_programming(direction, A, senses, b, c, l, u):
    # create an empty optimization problem
    prob = cp.Cplex()

    # add decision variables to the problem including their coefficients in objective and ranges
    prob.variables.add(obj = c.tolist(), lb = l.tolist(), ub = u.tolist())

    # define problem type
    if direction == "maximize":
        prob.objective.set_sense(prob.objective.sense.maximize)
    else:
        prob.objective.set_sense(prob.objective.sense.minimize)

    # add constraints to the problem including their directions and right-hand side values
    prob.linear_constraints.add(senses = senses.tolist(), rhs = b.tolist())

    # add coefficients for each constraint
    row_indices, col_indices = A.nonzero()
    prob.linear_constraints.set_coefficients(zip(row_indices.tolist(), col_indices.tolist(), A.data.tolist()))

    # solve the problem
    prob.solve()

    # check the solution status
    print(prob.solution.get_status())
    print(prob.solution.status[prob.solution.get_status()])

    # get the solution
    x_star = prob.solution.get_values()
    obj_star = prob.solution.get_objective_value()

    return(x_star, obj_star)

In [80]:
def minimum_cost_flow_problem(weights_file, values_file, capacity_file):
    
    # load the required materials 
    weights = np.loadtxt(weights_file)
    print(weights)
    values = np.loadtxt(values_file)
    print(values)
    capacity = np.loadtxt(capacity_file)
    print(capacity)

    N = values.shape[0] 
    print(N)

    #coefficients of objective function 
    c = values[:].astype(int)
    print(c)

    #equality symbols 
    senses = np.repeat("L", 1)
    print(senses)

    # right hand side values 
    b = np.repeat(capacity,1)

    #lower and upper bound values
    l = np.repeat(0, N)
    u = np.repeat(1, N)
    print(b)
    print(l)
    print(u)

    #defining A matrix 
    A = np.matrix(weights.astype(int))
    print(A)
    aij = np.repeat(weights, N)
    row = np.repeat(0, N)
    col = np.array(range(N))

    prob = cp.Cplex()

    # add decision variables to the problem including their coefficients in objective and ranges
    prob.variables.add(obj = c.tolist(), lb = l.tolist(), ub = u.tolist())

    # define problem type

    prob.objective.set_sense(prob.objective.sense.minimize)

    # add constraints to the problem including their directions and right-hand side values
    prob.linear_constraints.add(senses = senses, rhs = b)

    # add coefficients for each constraint
    row_indices, col_indices = A.nonzero()
    prob.linear_constraints.set_coefficients(zip(row.tolist(), col.tolist(), aij.tolist()))

    # solve the problem
    prob.solve()

    # check the solution status
    print(prob.solution.get_status())
    print(prob.solution.status[prob.solution.get_status()])

    # get the solution
    x_star = prob.solution.get_values()
    obj_star = prob.solution.get_objective_value()

    print(x_star)
    print(obj_star)
    return(x_star, obj_star)

In [81]:
x_star, obj_star = minimum_cost_flow_problem("weights.txt", "values.txt", "capacity.txt")

[3. 4. 2. 5. 2. 6.]
[1. 2. 3. 4. 5. 6.]
60.0
6
[1 2 3 4 5 6]
['L']
[60.]
[0 0 0 0 0 0]
[1 1 1 1 1 1]
[[3 4 2 5 2 6]]
Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de
CPXPARAM_Read_DataCheck                          1
Tried aggregator 1 time.
LP Presolve eliminated 1 rows and 6 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)
1
optimal
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
0.0
